services:
  ghostwarp:
    image: tigsus/gw-scripts:1.0.20210914-8
    container_name: gw-scripts
    cap_add:
      - NET_ADMIN
      #- SYS_MODULE # OPTIONAL
    #volumes:
      #- ./data:/config
      #- ./globals.env:/gw-scripts/globals.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - SERVERURL=myserver.example.com
      - SERVERPORT=51820
      - SERVER_MODE=true
      - LOG_CONFS=false
    restart: unless-stopped
