services:
  gw-scripts:
    image: tigsus/gw-scripts:1.0.20210914-12
    container_name: ${GWContainerName}
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${GWContainerWGTimeZone:-America/Chicago}
    volumes:
      - ./required.env:/gw-scripts/globals.env
    ports:
      - "${GWHostWGPort:-51820}:51820/udp"
    sysctls:
      - net.ipv4.ip_forward=1
    restart: unless-stopped
