version: '3.8' # Optional but recommended to specify version for compatibility

services:
  ghostwarp:
    image: tigsus/gw-scripts:1.0.20210914-7
    container_name: ${GWContainerName}
    cap_add:
      - NET_ADMIN
      #- SYS_MODULE # Uncomment if required for additional WireGuard features
    volumes:
      - ./data/config:/config # Uncomment if you need persistent configuration data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${GWContainerWGTimeZone:-America/Chicago}  # Use the timezone from .env or default to Chicago
      - SERVERURL=${GWContainerWGServerUrl:-myserver.example.com}  # URL for the external server, default value as fallback
      - SERVERPORT=${GWContainerWGServerPort:-51820}  # Port for the external server, default value as fallback
      - INTERNAL_SUBNET=${GWContainerWGSubnet:-10.13.13.0}  # The wireguard vpn network created as an interface inside the container instance
      - SERVER_MODE=true
      - LOG_CONFS=false
    restart: unless-stopped
    ports:
      - "51820:51820/udp"  # WireGuard server port
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      default:
        ipv4_address: ${GWDockerHostContainerIP}

networks:
  default:
    name: ${GWDockerHostNetName}
    external: true  # Assumes the network is already created
